cmake_minimum_required(VERSION 3.31)
project(xCONF C)

set(CMAKE_C_STANDARD 23)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/output)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/output)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/output)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE INTERNAL "")

if (${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_CURRENT_SOURCE_DIR})
    set(TARGET_PREFIX "")
else ()
    set(TARGET_PREFIX "xCONF_")
endif ()

add_compile_options("-funsigned-char")
add_compile_options("-O3" "-Os")
add_compile_options("-Wall" "-Wextra" "-Werror")
if (WIN32)
    add_compile_options("-Wno-format")
endif ()
if (ENABLE_TEST_COV)
    add_compile_options("-fprofile-arcs" "-ftest-coverage")
endif ()
if (ENABLE_GPROF)
    add_compile_options("-pg")
    add_link_options("-pg")
endif ()

set(XCONF_GENERATED_DIR "${CMAKE_CURRENT_SOURCE_DIR}/grammar/generated")
if(NOT EXISTS ${XCONF_GENERATED_DIR})
    message(STATUS "'${XCONF_GENERATED_DIR}' doesn't exist or not complete, generate grammar action table.")
    execute_process(COMMAND /bin/sh ${CMAKE_CURRENT_SOURCE_DIR}/codegen.sh
            WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
else()
    message(STATUS "${XCONF_GENERATED_DIR} exists, skip to generate grammar action table.")
endif()

if (NOT TARGET meman)
    include_directories(meman)
    aux_source_directory(meman MEMAN_SRC)
    add_library(meman STATIC ${MEMAN_SRC})
    link_libraries(meman)
endif ()

include_directories(include)

aux_source_directory(utils XCONF_UTILS_SRC)

file(GLOB_RECURSE XCONF_GRAMMAR_SRC RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} grammar/*.c grammar/*.h)
add_library(${TARGET_PREFIX}grammar STATIC ${XCONF_GRAMMAR_SRC} ${XCONF_UTILS_SRC})
target_include_directories(${TARGET_PREFIX}grammar PRIVATE grammar utils)

aux_source_directory(compose XCONF_COMPOSE_SRC)
add_library(${TARGET_PREFIX}compose STATIC ${XCONF_COMPOSE_SRC})
target_link_libraries(${TARGET_PREFIX}compose PRIVATE ${TARGET_PREFIX}grammar)
target_include_directories(${TARGET_PREFIX}compose PRIVATE grammar)

aux_source_directory(driver XCONF_DRIVER_SRC)
add_library(xCONF STATIC ${XCONF_DRIVER_SRC})
target_link_libraries(xCONF PRIVATE ${TARGET_PREFIX}grammar ${TARGET_PREFIX}compose)
target_include_directories(xCONF PRIVATE grammar compose)

add_executable(debug test/debug.c ${XCONF_UTILS_SRC})
target_include_directories(debug PRIVATE utils)
